env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"

task:
    name: aosp
    timeout_in: 180m
    container:
      image: apon77/aosp:latest
      cpu: 8
      memory: 32G
    sync_script:
      - ./sync
    monitor_background_script:
      - ./monitor
    build_script:
      - ./build
