#!/bin/bash

mkdir -p /tmp/rom
cd /tmp/rom

#repo init -q --no-repo-verify --depth=1 -u git://github.com/DotOS/manifest.git -b dot11 -g default,-device,-mips,-darwin,-notdefault
#git clone https://github.com/RahulPalXDA/G_manifest.git --depth 1 -b dot11 .repo/local_manifests
#repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 30 || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 4
